<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('locations')->insert([

            // ===== VIỆT NAM =====
            ['country_id'=>1,'name'=>'Bà Nà Hills','description'=>'Quần thể du lịch nghỉ dưỡng và vui chơi giải trí hàng đầu Việt Nam.','content'=>'Tọa lạc ở độ cao 1.487m so với mực nước biển, nơi đây được mệnh danh là đường lên tiên cảnh với khí hậu 4 mùa trong một ngày. Nổi bật nhất là Cầu Vàng (Golden Bridge) được nâng đỡ bởi đôi bàn tay khổng lồ, làng Pháp cổ kính và hầm rượu Debay xuyên lòng núi.','address'=>'Xã Hòa Ninh, Huyện Hòa Vang','province'=>'Đà Nẵng','lat'=>15.9950,'lng'=>107.9880,'image_url'=>'https://vcdn1-dulich.vnecdn.net/2025/04/10/BNtop-1744279080-7298-1744280762.jpg?w=0&h=0&q=100&dpr=2&fit=crop&s=fa5s51Vg2pTOCMq-gWBuTA','views_count'=>15,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Biển Mỹ Khê','description'=>'Một trong sáu bãi biển quyến rũ nhất hành tinh do tạp chí Forbes bình chọn.','content'=>'Nổi tiếng với bãi cát trắng mịn trải dài, sóng biển ôn hòa và làn nước ấm quanh năm. Đây là địa điểm lý tưởng để tham gia các hoạt động thể thao biển như lướt ván, lặn ngắm san hô hoặc đơn giản là ngắm bình minh trên biển tuyệt đẹp.','address'=>'Phường Phước Mỹ, Quận Sơn Trà','province'=>'Đà Nẵng','lat'=>16.0678,'lng'=>108.2470,'image_url'=>'https://api.sovaba.travel/uploads/Bien_my_khe_da_nang_4a33014aa5.jpg','views_count'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Hồ Gươm','description'=>'Trái tim của thủ đô Hà Nội, nơi giao thoa giữa lịch sử và nhịp sống hiện đại.','content'=>'Còn có tên gọi là Hồ Hoàn Kiếm, gắn liền với truyền thuyết vua Lê Lợi trả gươm báu cho Rùa Thần. Xung quanh hồ có các di tích lịch sử quan trọng như đền Ngọc Sơn, cầu Thê Húc, tháp Rùa và khu phố cổ sầm uất.','address'=>'Phường Hàng Trống, Quận Hoàn Kiếm','province'=>'Hà Nội','lat'=>21.0287,'lng'=>105.8523,'image_url'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/H%E1%BB%93_Ho%C3%A0n_Ki%E1%BA%BFm.jpg/1920px-H%E1%BB%93_Ho%C3%A0n_Ki%E1%BA%BFm.jpg','views_count'=>36,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Phố cổ Hội An','description'=>'Di sản văn hóa thế giới với vẻ đẹp hoài cổ và sự tĩnh lặng bình yên.','content'=>'Từng là thương cảng sầm uất vào thế kỷ 17, Hội An ngày nay bảo tồn gần như nguyên vẹn hơn 1000 di tích kiến trúc từ phố xá, nhà cửa đến đình chùa. Điểm nhấn là Chùa Cầu, các hội quán Trung Hoa và lễ hội thả đèn hoa đăng trên sông Hoài.','address'=>'Phường Minh An, Thành phố Hội An','province'=>'Quảng Nam','lat'=>15.8801,'lng'=>108.3380,'image_url'=>'https://images2.thanhnien.vn/528068263637045248/2023/4/4/hoi-an-1680591517857660432696.jpg','views_count'=>39,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Fansipan','description'=>'Chinh phục nóc nhà Đông Dương với độ cao 3.143m đầy thử thách.','content'=>'Nằm trong dãy núi Hoàng Liên Sơn, Fansipan mang đến trải nghiệm tuyệt vời khi đi qua những cánh rừng nguyên sinh bằng cáp treo đạt nhiều kỷ lục thế giới. Từ đỉnh núi, du khách có thể săn mây và ngắm nhìn toàn cảnh dãy núi hùng vĩ.','address'=>'Thị xã Sa Pa, Huyện Sa Pa','province'=>'Lào Cai','lat'=>22.3033,'lng'=>103.7756,'image_url'=>'https://media.vietravel.com/images/Content/du-lich-fansipan-5.png','views_count'=>23,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Vịnh Hạ Long','description'=>'Kỳ quan thiên nhiên thế giới với hàng ngàn đảo đá vôi kỳ vĩ.','content'=>'Hạ Long sở hữu hệ thống hang động tuyệt đẹp như hang Sửng Sốt, động Thiên Cung cùng các làng chài ven biển. Du khách có thể trải nghiệm ngủ đêm trên du thuyền giữa lòng vịnh để cảm nhận hết vẻ đẹp huyền ảo của di sản thiên nhiên này.','address'=>'Thành phố Hạ Long','province'=>'Quảng Ninh','lat'=>20.9101,'lng'=>107.1839,'image_url'=>'https://nhandan.vn/special/30-nam-mot-chang-duong-di-san-Vinh-Ha-Long/assets/HLCklusX0n/things-to-do-in-ha-long-bay-banner-1-1920x1080.jpg','views_count'=>24,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Đà Lạt','description'=>'Thành phố ngàn hoa với không gian mộng mơ và kiến trúc Pháp cổ điển.','content'=>'Đà Lạt thu hút du khách bởi khí hậu ôn đới mát mẻ, những đồi thông bạt ngàn và các thung lũng đầy hoa. Các địa danh không thể bỏ qua gồm Hồ Xuân Hương, Thung lũng Tình Yêu, Ga Đà Lạt và những quán cà phê view đồi núi cực chill.','address'=>'Thành phố Đà Lạt','province'=>'Lâm Đồng','lat'=>11.9404,'lng'=>108.4583,'image_url'=>'https://images2.thanhnien.vn/528068263637045248/2023/9/11/568976h1-1694451569790557720062.jpg','views_count'=>53,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>1,'name'=>'Phú Quốc','description'=>'Thiên đường nghỉ dưỡng đảo Ngọc với những bãi biển hoang sơ.','content'=>'Đảo lớn nhất Việt Nam sở hữu những bãi tắm đẹp như Bãi Sao, Bãi Trường. Bên cạnh đó, du khách còn được khám phá các cơ sở sản xuất nước mắm truyền thống, vườn tiêu xanh ngắt và thưởng thức hải sản tươi ngon tại chợ đêm.','address'=>'Thành phố Phú Quốc','province'=>'Kiên Giang','lat'=>10.2899,'lng'=>103.9840,'image_url'=>'https://ik.imagekit.io/tvlk/blog/2025/02/YxzFGZxQ-kinh-nghiem-du-lich-phu-quoc-6.jpg','views_count'=>17,'created_at'=>now(),'updated_at'=>now()],

            // ===== THÁI LAN =====
            ['country_id'=>2,'name'=>'Grand Palace','description'=>'Cung điện Hoàng gia Thái Lan - biểu tượng kiến trúc rực rỡ của Bangkok.','content'=>'Được xây dựng từ năm 1782, đây là một quần thể kiến trúc tinh xảo kết hợp giữa phong cách truyền thống Thái Lan và phương Tây. Nơi đây từng là nơi ở của các vị vua và hiện nay là nơi tổ chức các nghi lễ hoàng gia quan trọng nhất của xứ sở Chùa Vàng.','address'=>'Na Phra Lan Road, Phra Borom Maha Ratchawang, Phra Nakhon','province'=>'Bangkok','lat'=>13.7500,'lng'=>100.4913,'image_url'=>'https://haidangtravel.com/image/blog/Cung_%C4%91ie%CC%A3%CC%82n.jpg','views_count'=>34,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>2,'name'=>'Wat Arun','description'=>'Chùa Bình Minh - kiệt tác kiến trúc nằm bên bờ sông Chao Phraya.','content'=>'Ngôi chùa nổi bật với tòa tháp cao hơn 70m được khảm bằng sứ màu và thủy tinh tinh xảo. Wat Arun đẹp nhất vào lúc hoàng hôn khi ánh nắng chiếu rọi lên những mảnh sứ lấp lánh và thắp sáng rực rỡ cả một góc sông.','address'=>'158 Thanon Wang Doem, Wat Arun, Bangkok Yai','province'=>'Bangkok','lat'=>13.7437,'lng'=>100.4889,'image_url'=>'https://cdn3.ivivu.com/2019/03/ngoi-chua-tuyet-dep-o-thai-lan-duoc-gioi-tre-ran-ran-check-in-ivivu-2-1024x683.jpg','views_count'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>2,'name'=>'Phuket Beach','description'=>'Hòn ngọc của biển Andaman với những bãi cát trắng trải dài.','content'=>'Phuket nổi tiếng với các bãi biển như Patong, Kata và Karon. Nơi đây không chỉ có thiên nhiên xinh đẹp mà còn sôi động với các hoạt động giải trí về đêm, thể thao dưới nước và những khu nghỉ dưỡng sang trọng bậc nhất thế giới.','address'=>'Patong, Kathu District','province'=>'Phuket','lat'=>7.8804,'lng'=>98.3923,'image_url'=>'https://www.royalcaribbean.com/media-assets/pmc/content/dam/excalibur/digital-stock/royalty-free/shutterstock/2022/2022-08/stock-photo-beautiful-crystal-clear-water-at-pileh-bay-at-phi-phi-island-near-phuket-thailand-735390361.jpg?w=1440','views_count'=>49,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>2,'name'=>'Chiang Mai Old City','description'=>'Khu phố cổ nghìn năm với những ngôi chùa cổ kính và tường thành bao quanh.','content'=>'Là thủ phủ của vương quốc Lanna xưa, khu phố cổ Chiang Mai thu hút du khách bởi không gian yên bình, những quán cà phê nghệ thuật và các ngôi chùa linh thiêng như Wat Chedi Luang. Đây là nơi diễn ra lễ hội thả đèn trời tuyệt đẹp.','address'=>'Si Phum Subdistrict, Mueang Chiang Mai District','province'=>'Chiang Mai','lat'=>18.7883,'lng'=>98.9853,'image_url'=>'https://palmvilla-chiangmai.com/wp-content/uploads/2023/11/184d7edf-5c3a-470c-8529-b0085d6d5b0e.jpg','views_count'=>24,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>2,'name'=>'Ayutthaya','description'=>'Cố đô cổ kính - Di sản văn hóa thế giới được UNESCO công nhận.','content'=>'Từng là kinh đô của Thái Lan trong hơn 400 năm, Ayutthaya mang vẻ đẹp trầm mặc với những tàn tích đền đài bằng gạch đỏ. Điểm nhấn nổi tiếng nhất là đầu tượng Phật được bao quanh bởi rễ cây cổ thụ tại Wat Mahathat.','address'=>'Pratuchai Subdistrict, Phra Nakhon Si Ayutthaya District','province'=>'Ayutthaya','lat'=>14.3532,'lng'=>100.5689,'image_url'=>'https://mini-adventures.com/wp-content/uploads/2024/10/ayutthaya-day-trip-46.jpg','views_count'=>15,'created_at'=>now(),'updated_at'=>now()],

            // ===== LÀO =====
            ['country_id'=>3,'name'=>'Luang Prabang','description'=>'Cố đô yên bình của Lào - Di sản văn hóa thế giới UNESCO.','content'=>'Tọa lạc tại ngã ba sông Mekong và sông Nam Khan, Luang Prabang là trung tâm tâm linh của Lào với hàng chục ngôi chùa cổ kính như Wat Xieng Thong. Nơi đây nổi tiếng với nghi lễ khất thực (Alms Giving) diễn ra mỗi sáng sớm và bầu không khí thanh bình, đậm chất Pháp cổ.','address'=>'Sisavangvong Road, Old Town','province'=>'Luang Prabang','lat'=>19.8856,'lng'=>102.1340,'image_url'=>'https://media.vietravel.com/images/Content/co-do-luang-prabang-dia-diem-du-lich-lao-mua-he-1.png','views_count'=>37,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>3,'name'=>'Vientiane','description'=>'Thủ đô Viêng Chăn - Sự kết hợp giữa tâm linh và nét hiện đại bên dòng Mekong.','content'=>'Viêng Chăn là thủ đô nhỏ gọn và yên tĩnh nhất Đông Nam Á. Các điểm tham quan biểu tượng bao gồm Pha That Luang (Tháp Vàng) - biểu tượng của quốc gia, Khải hoàn môn Patuxai và công viên tượng Phật Xieng Khuan đầy bí ẩn.','address'=>'Lane Xang Avenue, Chanthabouly District','province'=>'Vientiane','lat'=>17.9757,'lng'=>102.6331,'image_url'=>'https://cdn.sanity.io/images/nxpteyfv/goguides/dbba1c52390e369f84f5798e949e17793ce6a7e2-1600x1066.jpg','views_count'=>45,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>3,'name'=>'Kuang Si Falls','description'=>'Thác nước nhiều tầng với làn nước xanh ngọc bích tuyệt đẹp.','content'=>'Nằm giữa khu rừng nguyên sinh, Kuang Si là thác nước đá vôi đổ xuống các hồ chứa tự nhiên trong xanh như ngọc. Tại đây, du khách có thể bơi lội, đi bộ xuyên rừng hoặc ghé thăm khu bảo tồn gấu đen quý hiếm ngay lối vào thác.','address'=>'Ban Thapene Village, 29km South of Luang Prabang','province'=>'Luang Prabang','lat'=>19.7496,'lng'=>101.9976,'image_url'=>'https://tourismluangprabang.org/wp-content/uploads/2022/06/kuang-si-2.jpg','views_count'=>50,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>3,'name'=>'Plain of Jars','description'=>'Cánh đồng Chum - Di tích khảo cổ bí ẩn hàng ngàn năm tuổi.','content'=>'Hàng ngàn chiếc chum bằng đá khổng lồ nằm rải rác trên các cánh đồng tại tỉnh Xieng Khouang vẫn là một ẩn số đối với các nhà khoa học. Đây là một trong những địa điểm lịch sử quan trọng nhất của thời đại đồ sắt tại Đông Nam Á.','address'=>'Phonsavan, Paek District','province'=>'Xieng Khouang','lat'=>19.4333,'lng'=>103.2000,'image_url'=>'https://vilandtravel.com/files/images/Destination/Laos/Plain%20Of%20Jars/What-cultural-significance-do-the-Plain-of-Jars-hold-in-Laos.jpg','views_count'=>69,'created_at'=>now(),'updated_at'=>now()],

            // ===== CAMPUCHIA =====
            ['country_id'=>4,'name'=>'Angkor Wat','description'=>'Kỳ quan tôn giáo lớn nhất thế giới và là biểu tượng tự hào của Campuchia.','content'=>'Được xây dựng vào thế kỷ 12, Angkor Wat là đỉnh cao của kiến trúc Khmer với những tác phẩm chạm khắc đá tinh xảo. Đây không chỉ là một ngôi đền mà còn là một quần thể kiến trúc hùng vĩ, nơi du khách có thể ngắm bình minh tuyệt đẹp trên những ngọn tháp hình hoa sen.','address'=>'Angkor Archaeological Park, Krong Siem Reap','province'=>'Siem Reap','lat'=>13.4125,'lng'=>103.8670,'image_url'=>'https://upload.wikimedia.org/wikipedia/commons/f/f5/Buddhist_monks_in_front_of_the_Angkor_Wat.jpg','views_count'=>35,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>4,'name'=>'Phnom Penh','description'=>'Thủ đô sầm uất với sự kết hợp giữa kiến trúc Khmer truyền thống.','content'=>'Nằm tại ngã ba sông Tonle Sap và Mekong, Phnom Penh thu hút du khách bởi Cung điện Hoàng gia lộng lẫy, Chùa Bạc và các khu chợ nhộn nhịp. Đây cũng là nơi lưu giữ những trang sử quan trọng qua Bảo tàng Diệt chủng Tuol Sleng.','address'=>'Preah Sihanouk Blvd, Sangkat Charktomuk','province'=>'Phnom Penh','lat'=>11.5564,'lng'=>104.9282,'image_url'=>'https://admin.vov.gov.vn/UploadFolder/KhoTin/Images/UploadFolder/VOVVN/Images/sites/default/files/2025-08/things_to_do_in_phnom_penh_20250813105202.jpg','views_count'=>17,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>4,'name'=>'Koh Rong','description'=>'Đảo thiên đường với vẻ đẹp hoài sơ và làn nước xanh ngọc bích.','content'=>'Cách đất liền khoảng 25km, Koh Rong là nơi lý tưởng để trốn khỏi sự ồn ào. Đảo sở hữu những bãi cát trắng mịn trải dài như bãi Long Beach, các rạn san hô rực rỡ và những ngôi làng chài yên bình ven biển.','address'=>'Koh Rong Island, Mittakpheap District','province'=>'Sihanoukville','lat'=>10.7200,'lng'=>103.2500,'image_url'=>'https://wetrek.vn/pic/Service/haha.vnk@gmail.com/images/Kinh-nghiem-du-lich-Koh-Rong.jpg','views_count'=>70,'created_at'=>now(),'updated_at'=>now()],

            // ===== INDONESIA =====
            ['country_id'=>5,'name'=>'Bali','description'=>'Thiên đường nghỉ dưỡng quyến rũ với sự kết hợp giữa biển xanh và văn hóa Hindu độc đáo.','content'=>'Được mệnh danh là Đảo của các vị thần, Bali thu hút du khách bởi những bãi biển tuyệt đẹp tại Kuta, ruộng bậc thang xanh ngát ở Ubud và những ngôi đền linh thiêng ven biển như Tanah Lot. Đây là điểm đến lý tưởng cho cả nghỉ dưỡng sang trọng lẫn du lịch trải nghiệm.','address'=>'Ubud, Gianyar Regency','province'=>'Bali','lat'=>-8.3405,'lng'=>115.0920,'image_url'=>'https://upload.wikimedia.org/wikipedia/commons/7/77/Pura_Ulun_Danu_Bratan%2C_2022.jpg','views_count'=>28,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>5,'name'=>'Jakarta','description'=>'Thủ đô sôi động của Indonesia, nơi giao thoa giữa hiện đại và truyền thống.','content'=>'Jakarta là trung tâm kinh tế, chính trị lớn nhất đất nước với những tòa nhà chọc trời san sát các khu phố cổ. Những điểm đến không thể bỏ qua gồm Đài tưởng niệm quốc gia Monas, khu phố cổ Kota Tua và các trung tâm thương mại sầm uất bậc nhất Đông Nam Á.','address'=>'Jalan Medan Merdeka, Central Jakarta','province'=>'Jakarta','lat'=>-6.2088,'lng'=>106.8456,'image_url'=>'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/depositphotos93389286xl-1764121082964.jpg','views_count'=>13,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>5,'name'=>'Borobudur','description'=>'Ngôi đền Phật giáo lớn nhất thế giới - Kỳ quan khảo cổ đầy tự hào.','content'=>'Được xây dựng từ thế kỷ thứ 9, Borobudur là một quần thể tháp chuông khổng lồ với hàng ngàn bức phù điêu chạm khắc tinh xảo kể về cuộc đời đức Phật. Đứng từ đỉnh đền vào lúc bình minh, du khách sẽ được chiêm ngưỡng khung cảnh kỳ ảo giữa làn sương mù và núi non.','address'=>'Jl. Badrawati, Borobudur, Magelang Regency','province'=>'Central Java','lat'=>-7.6079,'lng'=>110.2038,'image_url'=>'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/adsggf-1756434391048.jpg','views_count'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>5,'name'=>'Komodo Island','description'=>'Vườn quốc gia Komodo - Ngôi nhà duy nhất của loài rồng đất khổng lồ.','content'=>'Là một di sản thế giới UNESCO, đảo Komodo không chỉ nổi tiếng với loài rồng Komodo quý hiếm mà còn sở hữu những bãi biển cát hồng (Pink Beach) độc đáo. Hệ sinh thái biển nơi đây cũng thuộc hàng phong phú nhất thế giới, lý tưởng cho việc lặn ngắm san hô.','address'=>'Komodo District, Manggarai Barat Regency','province'=>'East Nusa Tenggara','lat'=>-8.5500,'lng'=>119.4833,'image_url'=>'https://girleatworld.net/wp-content/uploads/2025/10/padar-island-simon-spring-kUjkV_NKczA-unsplash.jpg','views_count'=>14,'created_at'=>now(),'updated_at'=>now()],
            
            // ===== NHẬT BẢN (COUNTRY_ID: 6) =====
            ['country_id'=>6,'name'=>'Tokyo','description'=>'Thủ đô hiện đại bậc nhất thế giới, nơi giao thoa giữa công nghệ và truyền thống.','content'=>'Tokyo gây ấn tượng mạnh với nhịp sống hối hả, những tòa nhà chọc trời tại Shinjuku, giao lộ Shibuya sầm uất và những ngôi đền cổ kính như Senso-ji. Đây là trung tâm văn hóa, thời trang và ẩm thực hàng đầu, mang đến những trải nghiệm không bao giờ quên cho du khách.','address'=>'Shibuya City, Tokyo Prefecture','province'=>'Tokyo','lat'=>35.6762,'lng'=>139.6503,'image_url'=>'https://vikkibank.vn/wp-content/uploads/2025/05/du-lich-tokyo-1.jpg','views_count'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>6,'name'=>'Kyoto','description'=>'Cố đô ngàn năm tuổi - Linh hồn văn hóa và tâm linh của Nhật Bản.','content'=>'Kyoto bảo tồn nguyên vẹn những giá trị truyền thống với hàng ngàn ngôi chùa Phật giáo, đền thờ Thần đạo và những khu vườn Zen tĩnh lặng. Nổi bật nhất là chùa Vàng Kinkaku-ji, con đường rực rỡ cổng Torii tại đền Fushimi Inari và khu phố Geisha Gion cổ kính.','address'=>'Shimogyo Ward, Kyoto City','province'=>'Kyoto','lat'=>35.0116,'lng'=>135.7681,'image_url'=>'https://media.vietravel.com/images/Content/kinh-nghiem-du-lich-kyoto-1.png','views_count'=>30,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>6,'name'=>'Osaka','description'=>'Nhà bếp quốc dân - Thành phố cảng sôi động với văn hóa ẩm thực độc đáo.','content'=>'Osaka nổi tiếng với tính cách phóng khoáng của người dân và thiên đường ăn uống Dotonbori. Du khách không thể bỏ qua lâu đài Osaka hùng vĩ, công viên Universal Studios Japan và những món ăn đường phố đặc sắc như Takoyaki và Okonomiyaki.','address'=>'Chuo Ward, Osaka City','province'=>'Osaka','lat'=>34.6937,'lng'=>135.5023,'image_url'=>'https://res.klook.com/image/upload/fl_lossy.progressive,q_60/v1755071491/destination/rln18ze4qicniwhvxwu5.jpg','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>6,'name'=>'Mount Fuji','description'=>'Núi Phú Sĩ - Biểu tượng thiêng liêng và là nóc nhà của xứ sở Mặt trời mọc.','content'=>'Với độ cao 3.776m, núi Phú Sĩ là một di sản thế giới UNESCO và là nguồn cảm hứng nghệ thuật bất tận. Du khách có thể ngắm nhìn ngọn núi tuyết phủ trắng xóa từ các hồ nước xung quanh như Kawaguchiko hoặc thử thách bản thân bằng việc leo núi vào mùa hè.','address'=>'Kitayama, Fujinomiya City','province'=>'Shizuoka','lat'=>35.3606,'lng'=>138.7274,'image_url'=>'https://www.snowmonkeyresorts.com/wp-content/uploads/2024/09/30647475_m-2.jpg','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>6,'name'=>'Hokkaido','description'=>'Vùng đất của thiên nhiên hoang sơ, tuyết trắng và hải sản tươi ngon.','content'=>'Hokkaido thu hút du khách bởi phong cảnh thay đổi ngoạn mục theo mùa: những cánh đồng hoa oải hương màu tím tại Furano vào mùa hè và lễ hội băng tuyết Sapporo rực rỡ vào mùa đông. Đây cũng là nơi có những khu nghỉ dưỡng suối nước nóng (Onsen) tốt nhất Nhật Bản.','address'=>'Chuo Ward, Sapporo City','province'=>'Hokkaido','lat'=>43.2203,'lng'=>142.8635,'image_url'=>'https://images.trvl-media.com/place/6128244/814e6aa7-3cb3-4332-9a46-244053afa39f.jpg','views_count'=>28,'created_at'=>now(),'updated_at'=>now()],

            // ===== SINGAPORE (COUNTRY_ID: 1) =====
            ['country_id'=>7,'name'=>'Gardens by the Bay','description'=>'Công viên tương lai với hệ thống siêu cây khổng lồ và vườn kính hiện đại.','content'=>'Đây là biểu tượng mới của Singapore với ba khu vườn ven biển độc đáo. Du khách sẽ được chiêm ngưỡng Supertree Grove rực rỡ ánh sáng vào ban đêm, khám phá thác nước trong nhà tại Cloud Forest và hàng ngàn loài hoa ôn đới tại Flower Dome.','address'=>'18 Marina Gardens Drive','province'=>'Singapore','lat'=>1.2816,'lng'=>103.8636,'image_url'=>'https://media.vietravel.com/images/Content/Visiting-Gardens-by-the-Bay-Singapore.jpg','views_count'=>10,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>7,'name'=>'Sentosa Island','description'=>'Hòn đảo giải trí phức hợp hàng đầu với những trải nghiệm bất tận.','content'=>'Sentosa là thiên đường vui chơi giải trí với công viên chủ đề Universal Studios Singapore, thủy cung S.E.A. Aquarium lớn nhất thế giới và những bãi biển cát trắng mịn. Đây là địa điểm lý tưởng cho các gia đình và những ai yêu thích cảm giác mạnh.','address'=>'Sentosa Island, Southern Islands','province'=>'Singapore','lat'=>1.2494,'lng'=>103.8303,'image_url'=>'https://images.squarespace-cdn.com/content/v1/5be172e38f513032e447734b/1558366937124-5ZJ9AAZ5Z721YPY0T588/Sentosa-Picture.jpg','views_count'=>10,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>7,'name'=>'Merlion Park','description'=>'Nơi đặt bức tượng Sư tử biển - biểu tượng huyền thoại của quốc đảo.','content'=>'Nằm tại vịnh Marina, công viên là nơi đặt tượng Merlion phun nước hướng ra biển. Đây là điểm check-in không thể bỏ qua, nơi bạn có thể ngắm nhìn toàn cảnh tòa nhà Marina Bay Sands và tận hưởng làn gió mát từ vịnh biển.','address'=>'1 Fullerton Road, Downtown Core','province'=>'Singapore','lat'=>1.2868,'lng'=>103.8545,'image_url'=>'https://media.vietravel.com/images/Content/du-lich-merlion-park-1.png','views_count'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>7,'name'=>'Clarke Quay','description'=>'Khu bến cảng sầm uất với nhịp sống đêm sôi động bên dòng sông Singapore.','content'=>'Từng là một bến tàu giao thương, Clarke Quay ngày nay là trung tâm giải trí với các dãy nhà màu sắc rực rỡ, hàng loạt quán bar, nhà hàng cao cấp và các câu lạc bộ đêm. Du khách cũng có thể trải nghiệm đi du thuyền trên sông để ngắm nhìn thành phố.','address'=>'3 River Valley Road, Singapore River','province'=>'Singapore','lat'=>1.2906,'lng'=>103.8465,'image_url'=>'https://images.trvl-media.com/place/6270159/ddfebf21-9c90-4671-80c4-cdc120cd5860.jpg','views_count'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>7,'name'=>'Zoo Singapore','description'=>'Vườn thú tốt nhất thế giới với mô hình trưng bày mở gần gũi thiên nhiên.','content'=>'Vườn thú Singapore nổi tiếng với phong cách "mở", thay thế rào chắn bằng các hào nước và cảnh quan tự nhiên. Tại đây, bạn có thể ăn sáng cùng đười ươi, xem các buổi trình diễn động vật hấp dẫn và khám phá đời sống hoang dã một cách chân thực nhất.','address'=>'80 Mandai Lake Road','province'=>'Singapore','lat'=>1.4043,'lng'=>103.7930,'image_url'=>'https://strictlysingapore.com/wp-content/uploads/2025/02/EC63C5CE-6DA1-41AE-993F-D393EFD7AF2A.jpeg','views_count'=>12,'created_at'=>now(),'updated_at'=>now()],

            // ===== TRUNG QUỐC (COUNTRY_ID: 8) =====
            ['country_id'=>8,'name'=>'Vạn Lý Trường Thành','description'=>'Kỳ quan thế giới hùng vĩ và là biểu tượng vĩnh cửu của nền văn minh Trung Hoa.','content'=>'Trải dài hàng nghìn km qua các vùng núi non hiểm trở, đây là công trình phòng thủ quân sự vĩ đại nhất lịch sử. Du khách thường đến khu vực Bát Đạt Lĩnh hoặc Mộ Điền Dục để chiêm ngưỡng những đoạn thành nguyên vẹn nhất và ngắm nhìn cảnh quan núi non trùng điệp.','address'=>'Huairou District, 70km North of Beijing','province'=>'Beijing','lat'=>40.4319,'lng'=>116.5704,'image_url'=>'https://ik.imagekit.io/tvlk/blog/2023/09/van-ly-truong-thanh-22.jpg','views_count'=>10,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>8,'name'=>'Tử Cấm Thành','description'=>'Cung điện hoàng gia lớn nhất thế giới với kiến trúc cổ kính và quyền uy.','content'=>'Nằm giữa trung tâm Bắc Kinh, đây từng là nơi ở của 24 vị hoàng đế triều đại nhà Minh và nhà Thanh. Với hơn 9000 căn phòng chứa đựng vô số báu vật quốc gia, Tử Cấm Thành là minh chứng rõ nét nhất cho sự xa hoa và quyền lực của đế chế Trung Hoa xưa.','address'=>'4 Jingshan Front St, Dongcheng District','province'=>'Beijing','lat'=>39.9163,'lng'=>116.3972,'image_url'=>'https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/depositphotos63330705xl-1719201121689.jpg','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>8,'name'=>'Thượng Hải','description'=>'Thành phố hiện đại bậc nhất, nơi giao thoa giữa nét cổ điển và tương lai.','content'=>'Thượng Hải gây ấn tượng với bến Thượng Hải (The Bund) mang phong cách châu Âu thế kỷ 19 đối lập với những tòa nhà chọc trời tại Lục Gia Chủy. Đây là trung tâm kinh tế sầm uất, thiên đường mua sắm và là nơi có tháp truyền hình Minh Châu Phương Đông nổi tiếng.','address'=>'Wai Tan, Huangpu District','province'=>'Shanghai','lat'=>31.2304,'lng'=>121.4737,'image_url'=>'https://images2.thanhnien.vn/528068263637045248/2023/12/7/a1-17019461240531747351528.jpg','views_count'=>10,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>8,'name'=>'Hàng Châu','description'=>'Thành phố thơ mộng được ví như "Thiên đường hạ giới" của Trung Quốc.','content'=>'Hàng Châu nổi tiếng với Tây Hồ (West Lake) sở hữu vẻ đẹp hữu tình qua mọi mùa trong năm. Nơi đây còn là cái nôi của trà Long Tỉnh danh tiếng và những ngôi chùa cổ kính, mang đến không gian yên bình tách biệt với nhịp sống đô thị hối hả.','address'=>'Xihu District, Hangzhou City','province'=>'Zhejiang','lat'=>30.2741,'lng'=>120.1551,'image_url'=>'https://vigotour.com.vn/wp-content/uploads/2024/07/hang-chau-1.jpg','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],

            // ===== HÀN QUỐC (COUNTRY_ID: 9) =====
            ['country_id'=>9,'name'=>'Seoul','description'=>'Thủ đô năng động bậc nhất châu Á, nơi hội tụ giữa công nghệ tương lai và di sản lâu đời.','content'=>'Seoul là trái tim của Hàn Quốc với những tòa nhà chọc trời, trung tâm mua sắm sầm uất tại Myeongdong và những con phố nghệ thuật tại Hongdae. Thành phố này mang đến sự cân bằng hoàn hảo giữa nhịp sống hiện đại hối hả và vẻ đẹp bình yên bên dòng sông Hàn.','address'=>'Jongno-gu, Seoul City','province'=>'Seoul','lat'=>37.5665,'lng'=>126.9780,'image_url'=>'https://www.trieuhaotravel.vn/Uploads/files/ncvy/unnamed_29_.png_large.webp','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>9,'name'=>'Busan','description'=>'Thành phố cảng lớn nhất Hàn Quốc với những bãi biển tuyệt đẹp và hải sản tươi ngon.','content'=>'Busan nổi tiếng với bãi biển Haeundae quyến rũ, làng văn hóa Gamcheon rực rỡ sắc màu và chợ hải sản Jagalchi sầm uất. Đây là địa điểm lý tưởng để tận hưởng không khí biển trong lành và trải nghiệm những lễ hội điện ảnh quốc tế hàng năm.','address'=>'Haeundae-gu, Busan City','province'=>'Busan','lat'=>35.1796,'lng'=>129.0756,'image_url'=>'https://kavotravel.com/wp-content/uploads/2024/07/01-gettyimages-1746790723v2.jpg','views_count'=>10,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>9,'name'=>'Jeju Island','description'=>'Hòn đảo tình yêu với cảnh quan thiên nhiên kỳ vĩ được UNESCO công nhận.','content'=>'Đảo Jeju thu hút du khách bởi những bãi đá núi lửa độc đáo, thác nước tự nhiên và đỉnh núi Seongsan Ilchulbong ngắm bình minh cực đẹp. Khí hậu ôn hòa quanh năm khiến nơi đây trở thành thiên đường nghỉ dưỡng và tuần trăng mật hàng đầu.','address'=>'Jeju-si, Jeju-do','province'=>'Jeju','lat'=>33.4996,'lng'=>126.5312,'image_url'=>'https://media-gadventures.global.ssl.fastly.net/media-server/dynamic/blogs/posts/G-Adventures/2025/09/blog-jeju-island-korea-travel-guide-springtime-hiking.webp','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],
            ['country_id'=>9,'name'=>'Nami Island','description'=>'Hòn đảo lãng mạn với những hàng cây thơ mộng thay đổi sắc màu theo mùa.','content'=>'Đảo Nami nổi tiếng khắp thế giới qua bộ phim "Bản tình ca mùa đông". Với những con đường rợp bóng cây ngân hạnh vàng rực vào mùa thu hay tuyết trắng phủ kín vào mùa đông, nơi đây mang đến một không gian yên bình và đầy chất thơ cho các cặp đôi.','address'=>'1 Namisum-gil, Namsan-myeon, Chuncheon-si','province'=>'Gangwon','lat'=>37.7910,'lng'=>127.5250,'image_url'=>'https://www.agoda.com/wp-content/uploads/2018/10/Experience-Seoul_day-trips_Nami-Island-Namiseon.jpg','views_count'=>0,'created_at'=>now(),'updated_at'=>now()],
 
]);
    }
}